### ISSUE TITLE
Connector type is known? 

### ISSUE THREAD

**Issue by 01GOD** [henjin0/LIDAR_M1C1_mini_python_loder#1]
Hi, 

Thanks for posting that and that blog page also! I got one of those M1C1 Mini lidar modules today. 

What type of connector is that White connector? Is that an XH connector? I already have a USB to serial adapter for programming STM32, so I imagine that is obviously compatible. So I need to find out what type of connector that is. I guess it's maybe XH. 

Any info about that M1C1 Mini is appreciated. Thanks in advance! 

PS: I reside in Japan sometimes, so if in the same city when I am there can maybe meet sometime. Had met some Japanese engineers at the Maker Faire in shenzhen at the end of the past calendar year also.

**Comment by henjin0** [comment]
色々とご確認頂きありがとうございます！
私も確認してみましたが、コネクターの規格に関する情報が仕様書に明記されていないですね。
また、購入から数年以上経過していることから、もしかしたら発売した時期で変えているかもしれないので名言できないですね。私も確かXHで互換していたような記憶があります。
機会があったらメイカーフェアでお会いしましょう！

Thank you for checking everything!
I have also checked, but the information about the connector standard is not specified in the specification sheet.
Also, as it has been more than a few years since I bought it, I can't give you a name as they might have changed it at the time it was released. I seem to remember that they were compatible with XH.
If you have any opportunities, we'll see you at a  Maker Faire!

**Comment by 01GOD** [comment]
Thanks for answering. 1.25mm XH seems maybe correct.

**Comment by henjin0** [comment]
Close.
